IMAGE_FEATURES_append = " package-management"
IMAGE_FEATURES_append = " dev-pkgs"

IMAGE_INSTALL_append = " eltt2"
IMAGE_INSTALL_append = " i2c-tools"
IMAGE_INSTALL_append = " init-f75111"
IMAGE_INSTALL_append = " kernel-modules"
IMAGE_INSTALL_append = " lmsensors-libsensors"
IMAGE_INSTALL_append = " lmsensors-sensors"
IMAGE_INSTALL_append = " lmsensors-sensorsdetect"
IMAGE_INSTALL_append = " python python3"
IMAGE_INSTALL_append = " python3-pip"

